apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  labels:
    application: bank-of-anthos
    environment: development
    team: ai
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: ai-agent
    application: bank-of-anthos
    environment: development
    team: ai
    tier: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  labels:
    application: bank-of-anthos
    environment: development
    team: ai
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
      application: bank-of-anthos
      environment: development
      team: ai
      tier: backend
  template:
    metadata:
      labels:
        app: ai-agent
        application: bank-of-anthos
        environment: development
        team: ai
        tier: backend
    spec:
      serviceAccountName: bank-of-anthos
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ai-agent
          image: ai-agent
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: v0.1.0
            - name: LOCAL_ROUTING_NUM
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: LOCAL_ROUTING_NUM
            - name: PUB_KEY_PATH
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: PUB_KEY_PATH
            - name: BALANCES_API_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-api-config
                  key: BALANCES_API_ADDR
            - name: TRANSACTIONS_API_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-api-config
                  key: TRANSACTIONS_API_ADDR
            - name: USE_VERTEX_AI
              value: "false"
            - name: LOG_LEVEL
              value: info
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: publickey
              mountPath: /tmp/.ssh
              readOnly: true
      volumes:
        - name: publickey
          secret:
            secretName: jwt-key
            items:
              - key: jwtRS256.key.pub
                path: publickey
