apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    application: bank-of-anthos
    environment: development
    team: payments
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: paymentservice
    application: bank-of-anthos
    environment: development
    team: payments
    tier: backend
  ports:
    - name: http
      port: 6000
      targetPort: 6000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    application: bank-of-anthos
    environment: development
    team: payments
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
      application: bank-of-anthos
      environment: development
      team: payments
      tier: backend
  template:
    metadata:
      labels:
        app: paymentservice
        application: bank-of-anthos
        environment: development
        team: payments
        tier: backend
    spec:
      serviceAccountName: bank-of-anthos
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: paymentservice
          image: paymentservice
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: v0.1.0
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret-key
            - name: USERSERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-api-config
                  key: USERSERVICE_URL
            - name: LEDGERWRITER_URL
              valueFrom:
                configMapKeyRef:
                  name: service-api-config
                  key: LEDGERWRITER_URL
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: SMTP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: smtp-config
                  key: SMTP_SERVER
                  optional: true
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: smtp-config
                  key: SMTP_PORT
                  optional: true
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
                  optional: true
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
                  optional: true
            - name: FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: smtp-config
                  key: FROM_EMAIL
                  optional: true
            - name: LOG_LEVEL
              value: info
          ports:
            - containerPort: 6000
          readinessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: publickey
              mountPath: /tmp/.ssh
              readOnly: true
      volumes:
        - name: publickey
          secret:
            secretName: jwt-key
            items:
              - key: jwtRS256.key.pub
                path: publickey
